export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const SET_USER_DATA = "SET_USER_DATA";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const SET_INCOMES = "SET_INCOMES";
export const ADD_INCOME = "ADD_INCOME";
export const DELETE_INCOME = "DELETE_INCOME";
export const EDIT_INCOME = "EDIT_INCOME";
export const SET_CATEGORIES_DATA = "SET_CATEGORIES";

export const ADD_EXPENSE = "ADD_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const SET_PAGE = "SET_PAGE";

export const SET_EXPENSES = "SET_EXPENSES";
export const EDIT_EXPENSE = "EDIT_EXPENSE";
export const SET_TOTAL_ITEMS = "SET_TOTAL_ITEMS";
export const SET_LOADING = "SET_LOADING";
export const SET_LAST_VISIBLE = "SET_LAST_VISIBLE";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY";

export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SET_CATEGORY = "SET_CATEGORY";
